### ISSUE TITLE
Crash: Exporting animation for nonstandard skeletons (Demihuman, Monster)

### ISSUE THREAD

**Issue by gm-xanther** [Lunaretic/AnimationExporter#1]
A crash occurs when an animation for one of these skeletons is attempted to be exported, such as for mounts etc. 
It successfully finds the .pap and .sklb, the bug appears to be related to unexpected bone names.

Here is the error resulting when using these files for export: 

```
	"SkeletonPath":"chara/demihuman/d0002/skeleton/base/b0001/skl_d0002b0001.sklb",
	"AnimationPaths":[
		"chara/demihuman/d0002/animation/a0001/bt_common/resident/mount.pap",
	]
```

These files are the Magitek Armor mount. Also attempted this with Monsters with similar results, though Godbert can export Monsters successfully by itself, while it cannot export Demihumans.

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'j_sebo_a' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SaintCoinach.Graphics.Viewer.Interop.FbxExport.<>c__DisplayClass1_0.<ExportFbx>b__0(String n) in D:\Dev\SaintCoinach\SaintCoinach.Graphics.Viewer\Interop\FbxExport.cs:line 41
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SaintCoinach.Graphics.Viewer.Interop.FbxExport.ExportFbx(String fileName, Mesh[] ma, Skeleton skele, List`1 paps, Int32 mode) in D:\Dev\SaintCoinach\SaintCoinach.Graphics.Viewer\Interop\FbxExport.cs:line 39
   at Godbert.main.Main(String[] args) in D:\dev\AnimConverter\Program.cs:line 102
```

Thanks for reading, I hope this can be resolved somehow if you are still active on this!

**Comment by ChlorideCull** [comment]
A quick guess is that it's an issue on line 64: https://github.com/Lunaretic/AnimationExporter/blob/9bd262b96f25e762031b7373a284a2dafa206a32/Program.cs#L64

It needs a model that's rigged for the skeleton you're using, as far as I can tell. You could either make it pull this from the config by adding a property for it in `ConfigJson`, and replace that line with `var body = config.Body ?? "chara/equipment/e0000/model/c0101e0000_top.mdl";` to pull it from there if defined, or you can just change it to a different hardcoded value and recompile.

**Comment by TemperanceTempy** [comment]
I'm having a similar issue with this as well, i know its almost been a year but any sign that this might be fixed or updated on the main download? Or should I go ahead and download the git code instead and try and work with it from there?
